return {
  -- {
  --   "L3MON4D3/LuaSnip",
  --   keys = {
  --     {
  --       mode = { "i", "n" },
  --       "<C-t>",
  --       function()
  --         require("luasnip").expand()
  --       end,
  --     },
  --     {
  --       "<TAB>",
  --       mode = { "i", "s", "n" },
  --       function()
  --         local ls = require("luasnip")
  --         if ls.jumpable(1) then
  --           ls.jump(1)
  --         else
  --           return vim.api.nvim_replace_termcodes("<Tab>", true, true, true)
  --         end
  --       end,
  --     },
  --     {
  --       "<S-TAB>",
  --       mode = { "i", "s", "n" },
  --       function()
  --         local ls = require("luasnip")
  --
  --         if ls.jumpable(-1) then
  --           ls.jump(-1)
  --         else
  --           return vim.api.nvim_replace_termcodes("<S-Tab>", true, true, true)
  --         end
  --       end,
  --       { silent = true, description = "Jump snippet backwards" },
  --     },
  --   },
  -- },
}
